controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
home:
    path: /
    controller: App\Controller\HomeController::index
register:
    path: /register
    controller: App\Controller\RegistrationController::index
registration_success:
    path: /register/success
    controller: 'App\Controller\RegistrationController::registrationSuccess'